version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile.Dev
    env_file:
      - apps/web/.env
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - /app/apps/web/node_modules
      - ./apps/web:/app/apps/web
    networks:
      - app_network
  web-unit-test:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.Dev
    env_file:
      - apps/web/.env
    restart: always
    volumes:
      - /app/apps/web/node_modules
      - ./apps/web:/app/apps/web
    command: ["yarn", "run", "test:unit:dev", "--filter=web"]
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile.Dev
    env_file:
      - apps/api/.env.dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /app/apps/api/node_modules
      - ./apps/api:/app/apps/api
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
